### PR TITLE
Removing unuseful keywords process and memdump from names

### PR DESCRIPTION
**Pull request by Anipik**
Process and Memdump was not giving any useful info. So This PR removes them

### CODE REVIEW

**Comment by Anipik** [comment]
@DrewScoggins  I have added you as a reviewer in the ongoing helix api.

**Comment by Anipik** [comment]
@danmosemsft can you give it  a look ?

**Comment by DrewScoggins** [comment]
Why are you removing this?

**Comment by Anipik** [comment]
In the other Helix PR, there was feedback that they dont give any extra information. eg .dmp extension already suggests that its a dump file, so no need of specifying "memdump". There was similar argument for the "process"

**Pull request merged**
